<h3><?php echo $question->getQuestion(); ?></h3>

<form action="check-answer" method="post">
    <ul>
        <?php $solutions = $question->getSolutions(); ?>
        <?php foreach ($solutions as $id => $solution): ?>
            <li><input type="radio" name="id" value="<?php echo $id; ?>"> <?php echo $solution; ?></li>
        <?php endforeach; ?>
    </ul>

    <input type="submit" value="Submit">
</form>
